# Generated by Django 4.0.2 on 2022-02-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorType',
            new_name='categoryType',
        ),
    ]
